services:
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - data-platform

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --cores 2 --memory 2g
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    networks:
      - data-platform

  spark-client:
    image: apache/spark:3.5.3
    container_name: spark-client
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./jobs:/app/jobs
      - ./utils:/app/utils
      - ./data:/app/data
    working_dir: /app
    networks:
      - data-platform
    # Mantém o container vivo pra você rodar comandos nele
    command: tail -f /dev/null

networks:
  data-platform:
    driver: bridge